[project]
name = "md-searcher"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "langchain[google-genai]>=0.3.27",
    "scikit-learn>=1.7.1",
    "uvicorn>=0.35.0",
]
